name: publish gh-pages
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build-and-deploy-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.GH_PAGES }}
          TARGET_REPO: Meituan-Dianping/lyrebird
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: cd docs && npm install && npm run build && cd -
          BUILD_DIR: docs/.vuepress/dist
